"""
Django settings for Transcendance project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import socket

PUBLIC_KEY = os.getenv("PUBLIC_KEY")
PRIVATE_KEY = os.getenv("PRIVATE_KEY")
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS")
ALCHEMY_RPC = os.getenv("ALCHEMY_RPC")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zz5ovspc-uqvzrt1hc513=_p8ey=+j^ary0+54m=hs@3k=p77a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'rest_framework',
	'channels',
	'authentication',
	'game',
    'liveChat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',# Pour consigurer daphne pour trouver les fichier static
	#python manage.py collectstatic pour trouver les fichier static (Django le fait seul)
]

# Fonction pour recuperer l'adresse IP du poste sur lequel tourne le serveur et l'ajouter a CSRF_TRUSTED_ORIGINS
def get_local_ips():
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    return [f'http://{local_ip}:8443']

#Ajoute pour autoriser l'origne HTTPS (Schema / Nom D'Hote / Port) puisque utilisation d'un proxy
CSRF_TRUSTED_ORIGINS = get_local_ips() + [
    'https://localhost:8443',
    'https://127.0.0.1:8443',
	'https://10.25.1.3:8443',
]

ROOT_URLCONF = 'Transcendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'Transcendance.wsgi.application'
ASGI_APPLICATION = 'Transcendance.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db/db.sqlite3',
    }
}

#ilona
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.environ.get("DJANGO_DB_PATH", BASE_DIR / "db/db.sqlite3"),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'authentication.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]
# STATIC_URL est defini par defaut par Django et sert a specifier le prefixe URL que Django utilisera pour référencer les fichiers statiques.
# STATIC_ROOT est un chemin qui definit l'endroit où Django rassemblera tous les fichiers statiques après l'exécution de la commande collectstatic.
# La commande collectstatics est utilise par Django pour faire une copie de tout les fichiers statics et les place dans un dossier staticfiles a la racine du projet.
# Elle est utilisee en production puisque Django ne sert pas lui-meme les fichiers statiques pour des raisons de performances et de securite.
# L'utilisation d'un serveur web comme NGINX ou Apache serait judicieuse. Le serveur web utilisera alors cette commande pour servir les fichiers statiques a partir de STATIC_ROOT
# STATICFILES_DIRS est une liste de repertoires qui sera utiliser pour chercher les fichiers statiques supplementaires a ceux de chaque app Django.

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis-server', 6379)],#Utiliser ici le nom de service Docker de redis mis en place
            'capacity': 3000,  # Augmenter la capacité du canal
            'expiry': 120,     # Messages expirent après 1 minute
        },
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

#Ajoute pour la pagnination de DRF
REST_FRAMEWORK = {
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',#LimitOffsetPagination (plus avances)
	'PAGE_SIZE': 5,
}
