#Je fais un dockerfile presque vierge pour garder la flexibilite pour une eventuelle config de redis (meme si peu probable)
#Et pour garder une structure de projet claire
FROM redis:latest




#Pour creer et lancer individuellement le container
#docker build -t myredis .
#docker run -d --name redis-server myredis

