# Generated by Django 5.1 on 2024-11-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0002_message_lu_alter_message_expediteur_conversation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
    ]
