# Generated by Django 5.1 on 2024-11-05 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0003_alter_message_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='expediteur',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='destinataire',
            new_name='user_2',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages_destinataire', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
